services:
  postgres:
    image: postgres:16
    container_name: mrpdbcontainer
    restart: always
    environment:
      POSTGRES_USER: mrp_admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mrpdb
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: